[package]
name = "shuttle-service"
version = "0.17.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"
homepage = "https://www.shuttle.rs"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
cargo = { workspace = true, optional = true }
cargo_metadata = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
pipe = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
strfmt = "0.2.2"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"], optional = true }
toml = { workspace = true, optional = true  }
tracing = { workspace = true, optional = true }

[dependencies.shuttle-codegen]
workspace = true
optional = true

[dependencies.shuttle-common]
workspace = true
features = ["service"]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["codegen"]

codegen = ["shuttle-codegen/frameworks"]
builder = [
    "cargo",
    "cargo_metadata",
    "crossbeam-channel",
    "pipe",
    "tokio",
    "toml",
    "tracing",
]
