[package]
name = "sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
serde = "1.0.163"
shuttle-service = "0.16.0"
shuttle-common = { version = "0.16.0", path = "../../common" }
