[package]
name = "shuttle-sqlite"
version = "0.16.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
serde = "1.0.163"
shuttle-service = { version = "0.16.0", path = "../../service" }
sqlx = { version = "0.6.3", features = ["sqlite", "runtime-tokio-rustls"] }
thiserror = "1.0.40"
tracing = "0.1.37"
